#!/bin/sh
#
# TODO: Unused as of now

# Set device to be toggled
TOUCHPAD_KEYWORD='$touchpad_enabled'

# Check if device is currently enabled (1 = enabled, 0 = disabled)
DEVICE="$(hyprctl getoption ${TOUCHPAD_KEYWORD} | grep 'int: 1')"

if [ -z "$DEVICE" ]; then
	# if the device is disabled, then enable
  	notify-send -u normal "Enabling Touchpad"
	hyprctl keyword $HYPRLAND_VARIABLE true
else
	# if the device is enabled, then disable
	notify-send -u normal "Disabling Touchpad"
	hyprctl keyword $HYPRLAND_VARIABLE false
fi
