#!/bin/bash

iDIR="$HOME/.config/mako/icons"

# Get Volume
get_volume() {
	volume=$(wpctl get-volume @DEFAULT_SINK@ | sed "s/Volume: //")
	echo "$volume * 100" | bc -l
}


# Get icons
get_icon() {
	current=$(get_volume)
	if [[ "$current" -eq "0" ]]; then
		echo "$iDIR/volume-mute.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo "$iDIR/volume-low.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "$iDIR/volume-mid.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo "$iDIR/volume-high.png"
	fi
}

# Notify
notify_user() {
	# notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume : $(get_volume) %"
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -h int:value:$(get_volume) -h int:transient:1 --app-name=volume "🎧 Current Volume 🎧"
}

# Increase Volume
inc_volume() {
	wpctl set-mute @DEFAULT_SINK@ 0 
	wpctl set-volume @DEFAULT_SINK@ 0.05+ -l 1 && notify_user
	# pamixer -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
	wpctl set-mute @DEFAULT_SINK@ 0 
	wpctl set-volume @DEFAULT_SINK@ 0.05- -l 1 && notify_user
	# pamixer -d 5 && notify_user
}

# Toggle Mute
toggle_mute() {
	if ! wpctl get-volume @DEFAULT_SINK@ | grep -q "MUTED"; then
		wpctl set-mute @DEFAULT_SINK@ 1 && notify-send  --app-name=volume -h string:x-canonical-private-synchronous:sys-notify -u low  "🔈    Audio OFF    🔈"

	else
		wpctl set-mute @DEFAULT_SINK@ 0 && notify-send  --app-name=volume -h string:x-canonical-private-synchronous:sys-notify -u low  "🔊    Audio ON    🔊"
	fi
}

# Toggle Mic
toggle_mic() {
	if ! wpctl get-volume @DEFAULT_SOURCE@ | grep -q "MUTED"; then
		wpctl set-mute @DEFAULT_SOURCE@ 1 && notify-send  --app-name=volume -h string:x-canonical-private-synchronous:sys-notify -h int:transient:1 -u low  "🔐   Microphone OFF   🔐"
	else
		wpctl set-mute @DEFAULT_SOURCE@ 0 && notify-send  --app-name=volume -h string:x-canonical-private-synchronous:sys-notify -h int:transient:1 -u low "🎙️   Microphone ON    🎙️"
	fi
}
# Get icons
get_mic_icon() {
	current=$(wpctl get-volume @DEFAULT_SOURCE@)
	if [[ "$current" -eq "0" ]]; then
		echo "$iDIR/microphone.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo "$iDIR/microphone.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "$iDIR/microphone.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo "$iDIR/microphone.png"
	fi
}
# Notify
notify_mic_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -h int:value:$(get_mic_volume) -h int:transient:1 --app-name=volume "🎤 Current Mic Volume 🎤"
}

get_mic_volume() {
	volume=$(wpctl get-volume @DEFAULT_SOURCE@ | sed "s/Volume: //")
	echo "$volume * 100" | bc -l
}

# Increase MIC Volume
inc_mic_volume() {
	# pamixer --default-source -i 5 && notify_mic_user
	wpctl set-volume @DEFAULT_SOURCE@ 0.05+ -l 1 && notify_mic_user
}

# Decrease MIC Volume
dec_mic_volume() {
	# pamixer --default-source -d 5 && notify_mic_user
	wpctl set-volume @DEFAULT_SOURCE@ 0.05- -l 1 && notify_mic_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--mic-inc" ]]; then
	inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
	dec_mic_volume
else
	get_volume
fi
