set -g default-terminal "screen-256color"
set-option -sg escape-time 10
set -g mouse on
set-option -g renumber-windows on
set-option -g focus-events on


# split vertically
unbind %
bind | split-window -h

# split horizontally
unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.config/tmux/tmux.conf
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
set-window-option -g mode-keys vi

# copy
set -s copy-command 'wl-copy'
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

bind u attach-session -c "#{pane_current_path}"

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# vim navigation
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @minimal-tmux-bg "#9D01F2"
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-indicator-str " estiázō "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "bottom"

# Enables or disables the left and right status bar
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true

# expanded icon (fullscreen icon)
set -g @minimal-tmux-expanded-icon " 󰊓 "

# on all tabs (default is false)
# false will make it visible for the current tab only
set -g @minimal-tmux-show-expanded-icons-for-all-tabs true

# To add or remove extra text in status bar
set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra ""

# Not recommended to change these values
set -g @minimal-tmux-status-right "#S"
# set -g @minimal-tmux-status-left "breathe..."

# If getting strings cut in left status or right
# Here 20 is the length of the characters in the string
set -g status-right-length 20
set -g status-left-length 20

# session
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux session after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # auto-save sessions every 15 minutes
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

set -g @plugin 'niksingh710/minimal-tmux-status'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
