background {
    monitor =
    path = $HOME/Pictures/Wallpapers/marcus-possibility-reach.png
    contrast = 0.8916
    blur_passes = 3
    brightness = 0.7172
    color = rgb(106, 13, 173)
    vibrancy = 0.1696
    vibrancy_darkness = 0
}

# INPUT FIELD
input-field {
    monitor =
    size = 270, 60
    outline_thickness = 0
    outer_color = rgba(0, 0, 0, 1)
    dots_size = 0.1 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgba(200, 200, 200, 1)
    fade_on_empty = false
    font_family = feather Bold
    placeholder_text = <span foreground="##cdd6f4">    $USER</span>
    hide_input = false
    position = 0, -30
    halign = center
    valign = center
    zindex = 10
}

# time
label {
    monitor =
    text = cmd[update:1000] echo "$TIME12"
    color = rgba(200, 200, 200, 1.0)
    font_size = 35
    font_family = Fira Semibold
    position = 0, 70
    halign = center
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %d %b %y")"
    color = rgba(200, 200, 200, 1.0)
    font_size = 15
    font_family = feather normal
    position = 0, 35 
    halign = center
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}


# percentage
label {
    monitor =
    text = cmd[update:1000] echo -e "$(~/.config/scripts/battery_info percentage)"
    color = rgba(200, 200, 200, 1)
    font_size = 25
    font_family = feather bold
    position = 0, -50
    halign = center
    valign = top
}


# time left
label {
    monitor =
    text = cmd[update:1000] echo -e "$(~/.config/scripts/battery_info time)"
    color = rgba(200, 200, 200, 1)
    font_size = 15
    font_family = feather normal
    position = 0, -100
    halign = center
    valign = top
}

# profile
image {
    monitor =
    path = $HOME/Pictures/profile_x.jpg
    size = 240 # lesser side if not 1:1 ratio
    rounding = -1 # negative values mean circle
    border_size = 0
    border_color = rgb(221, 221, 221)
    rotate = 0 # degrees, counter-clockwise
    reload_time = -1 # seconds between reloading, 0 to reload with SIGUSR2
    position = 0, 150
    halign = center
    valign = center
}
